### ISSUE TITLE
如何更改post排序先显示最新文章

### ISSUE THREAD

**Issue by lartpang** [Haojen/hexo-theme-Claudia#17]
如题

现在是最早的文章在最开头，我想知道如何改成新文章在开头。

**Comment by lartpang** [comment]
OK,已经找到问题所在，是索引生成插件的设置问题。
将下面的排序方式改成下面就好。
```
index_generator:
  path: ''
  per_page: 10
  order_by: -date
```
