### ISSUE TITLE
installed search button failed

### ISSUE THREAD

**Issue by WeekiXu** [Haojen/hexo-theme-Claudia#49]
**Describe the bug**
已经配置了search，清理，生成，启动，并用chrome无痕模式，页面就是没有搜索按钮。
1. `npm install hexo-generator-searchdb --save`
2. _config.yml ，search.json/search.xml 都试了
```
search:
  path: search.json
  field: post
  format: html
  limit: 10000
```
3. themes/Claudia/_config.yml
```
local_search: 
  enable: true
  trigger: auto
  top_n_per_article: 1
```
4. 清理，生成，启动
```
hexo clean
hexo g
hexo s
```
